mutation CreateThought($content: String!, $status: String!) @auth(level: USER) {
  thought_insert(
    data: {
      content: $content,
      status: $status,
      createdAt_expr: "request.time",
      user: { id_expr: "auth.uid" }
    }
  )
}

mutation UpdateThought($id: UUID!, $status: String!) @auth(level: USER) {
  thought_update(
    key: { id: $id },
    data: { status: $status }
  )
}

mutation DeleteThought($id: UUID!) @auth(level: USER) {
  thought_delete(key: { id: $id })
}

query ListUserThoughts @auth(level: USER) {
  thoughts(where: { userId: { eq_expr: "auth.uid" } }) {
    id
    content
    status
    createdAt
    priority
  }
}