// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPY_ifNjbWMKQYhDsYxXgdOj4LS0ePpik',
    appId: '1:672452098948:web:994c98e23242ac04a63bd1',
    messagingSenderId: '672452098948',
    projectId: 'ecommerce-admin-panel-a6d87',
    authDomain: 'ecommerce-admin-panel-a6d87.firebaseapp.com',
    storageBucket: 'ecommerce-admin-panel-a6d87.firebasestorage.app',
    measurementId: 'G-2G3EENS2L9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMLsvabI73bFvP3oTV0yog9uQdN6poSAw',
    appId: '1:672452098948:android:fb215a46b1573f4ba63bd1',
    messagingSenderId: '672452098948',
    projectId: 'ecommerce-admin-panel-a6d87',
    storageBucket: 'ecommerce-admin-panel-a6d87.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHQfjR_fSvV3x6w0H8UUXil5rqV1dMw5c',
    appId: '1:672452098948:ios:865882a3f0cfd028a63bd1',
    messagingSenderId: '672452098948',
    projectId: 'ecommerce-admin-panel-a6d87',
    storageBucket: 'ecommerce-admin-panel-a6d87.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHQfjR_fSvV3x6w0H8UUXil5rqV1dMw5c',
    appId: '1:672452098948:ios:865882a3f0cfd028a63bd1',
    messagingSenderId: '672452098948',
    projectId: 'ecommerce-admin-panel-a6d87',
    storageBucket: 'ecommerce-admin-panel-a6d87.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceAdminPanel',
  );
}
