type User @table {
  email: String!
  createdAt: Timestamp!
  preferredReminderTime: Timestamp
}

type Thought @table {
  content: String!
  status: String!
  createdAt: Timestamp!
  releaseDate: Timestamp
  priority: Int
  user: User!
}

type Category @table {
  name: String!
  colorCode: String!
  user: User!
}

type ThoughtCategory @table(key: ["thought", "category"]) {
  thought: Thought!
  category: Category!
}

type ReflectSession @table {
  sessionDate: Timestamp!
  notes: String!
  user: User!
}